# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "reveal"
license = "MIT"
licenselink = "https://github.com/towry/reveal.hugo-theme/blob/master/LICENSE.md"
description = ""
homepage = "http://towry.me/"
tags = ["hugo", "theme"]
features = ["clean"]
min_version = 0.18

[author]
  name = "Towry Wang"
  homepage = "http://towry.me"
